version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: QWE!@#rty456
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080